### ISSUE TITLE
Invalid lines in .github/workflows/main.yml (gpucpp CI cannot run)

### ISSUE THREAD

**Issue by valassi** [mg5amcnlo/mg5amcnlo#47]
Hi @oliviermattelaer (and @hageboeck if you can see this), minor point: I just updated the gpucpp upstream and got an email that the CI for the gpucpp branch failed.

I am not sure at all if we need to have a CI here and what we want it to do, but as it is, there is plainly an error in the yaml
https://github.com/mg5amcnlo/mg5amcnlo/blob/aa37739bebe3d5a61e7bfa7f186921b07fa75d23/.github/workflows/main.yml#L6
```
# This is a basic workflow to help you get started with Actions

name: sync with bazaar

 Controls when the workflow will run
    branches: [ main LTS ]
on:
  # Triggers the workflow on push or pull request events but only for the 3.4.0 branch
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
```

I imagine that the "Controls" line is a comment?
The "branches" line in any case triggers an error
https://github.com/valassi/mg5amcnlo/actions/runs/4572706326/workflow
![image](https://user-images.githubusercontent.com/3473550/229058636-7f5655bf-d327-4071-90b1-57beb32d79cb.png)

Thanks Andrea
